# .streamlit/config.toml
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
base="light"
primaryColor="#4CAF50"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"